

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import useLocalStorage from './hooks/useLocalStorage';

// --- THEME CONTEXT ---
type Theme = 'light' | 'dark';

interface ThemeContextType {
  theme: Theme;
  toggleTheme: () => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const theme: Theme = 'light';

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('dark');
    root.classList.add('light');
  }, []);

  const toggleTheme = () => {
    // No-op. Dark mode is removed.
  };

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (context === undefined) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};

// --- LANGUAGE CONTEXT ---
type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en'], ...args: (string | number)[]) => string;
}

const translations = {
  en: {
    headerTitle: "MemoryCare",
    navHome: "Home",
    navMemoryLog: "Memory Log",
    navPlanner: "Planner",
    navLocation: "Location",
    navMyStory: "My Story",
    navSettings: "Settings",
    footerText: "MemoryCare © {year}",
    language: "Language",
    welcomeTitle: "Today's Dashboard",
    welcomeSubtitle: "Here's a summary of your day.",
    welcomeMessage: "This application is designed to help you manage your day, remember important information, and stay connected.",
    todaysSchedule: "Today's Schedule",
    noActivitiesToday: "No activities for today. Ready to plan?",
    goToPlanner: "Go to Planner",
    familiarFace: "A Familiar Face",
    noPeopleToAdd: "No one's here yet. Add a loved one.",
    goToMemoryLog: "Go to Memory Log",
    quickActions: "Quick Actions",
    featureMemoryLogTitle: "Memory Log",
    featureMemoryLogDesc: "Keep track of loved ones and daily thoughts.",
    featurePlannerTitle: "Activity Planner",
    featurePlannerDesc: "Schedule your daily activities with reminders.",
    featureLocationTitle: "Location Services",
    featureLocationDesc: "Get help with navigation and stay safe.",
    reminderTitle: "A Gentle Reminder",
    reminderText: "Take each day one step at a time. We are here to support you. If you need help, please reach out to a caregiver or family member.",
    pageTitleMemoryLog: "Memory Log",
    pageSubtitleMemoryLog: "Remember important people and record your daily thoughts.",
    personAddedSuccess: "{name} added successfully!",
    personUpdatedSuccess: "{name} updated successfully.",
    personDeletedInfo: "Person deleted.",
    confirmDeletePerson: "Are you sure you want to delete this person?",
    journalSavedSuccess: "Journal entry saved!",
    journalNoSpeechInfo: "No speech detected to save.",
    confirmDeleteJournal: "Are you sure you want to delete this journal entry?",
    journalDeletedInfo: "Journal entry deleted.",
    ttsNotSupportedError: "Text-to-speech is not supported on this device.",
    ttsLanguageUnavailableError: "A native voice for the selected language is not available on your device. Speech functionality is limited.",
    peopleSectionTitle: "People",
    addPersonButton: "Add Person",
    noPeopleYet: 'No people added yet. Click "Add Person" to get started.',
    recallButton: "Recall",
    editButton: "Edit",
    deleteButton: "Delete",
    personRecallSpeech: "This is {name}, who is your {relationship}. {keyInfo}",
    journalSectionTitle: "Daily Journal",
    journalDescription: "Record your thoughts, feelings, or activities for the day using your voice.",
    speechNotSupported: "Speech recognition is not supported in your browser.",
    listeningPlaceholder: "Listening...",
    recordedThoughtsPlaceholder: "Your recorded thoughts will appear here...",
    startRecordingButton: "Start Recording",
    stopRecordingButton: "Stop Recording",
    saveEntryButton: "Save Entry",
    pastEntriesTitle: "Past Entries:",
    readAloudButton: "Read Aloud",
    modalAddPersonTitle: "Add New Person",
    modalEditPersonTitle: "Edit {name}",
    formNameLabel: "Name",
    formRelationshipLabel: "Relationship",
    formPhotoUrlLabel: "Photo URL or Upload",
    formKeyInfoLabel: "Key Information",
    formCancelButton: "Cancel",
    formAddButton: "Add Person",
    formUpdateButton: "Update Person",
    formUploadButton: "Upload Photo",
    formRequiredAlert: "Name and relationship are required.",
    pageTitlePlanner: "Daily Activity Planner",
    pageSubtitlePlanner: "Schedule your activities and get timely reminders.",
    activityAddedSuccess: 'Activity "{name}" added.',
    activityUpdatedSuccess: 'Activity "{name}" updated.',
    activityDeletedInfo: "Activity deleted.",
    confirmDeleteActivity: "Are you sure you want to delete this activity?",
    remindSentInfo: 'Reminder for "{name}" sent.',
    ttsAlertMessage: "Text-to-speech not supported. Showing alert instead.",
    activityReminderSpeech: "Reminder: It's time for {name} at {time}. {description}",
    pushNotificationTitle: "Reminder: {name}",
    pushNotificationBody: "Scheduled for {time}",
    addActivityButton: "Add Activity",
    noActivitiesYet: 'No activities scheduled. Click "Add Activity" to plan your day.',
    remindButton: "Remind",
    modalAddActivityTitle: "Add New Activity",
    modalEditActivityTitle: "Edit Activity",
    formActivityNameLabel: "Activity Name",
    formTimeLabel: "Time (HH:MM)",
    formDescriptionLabel: "Description (Optional)",
    formRecurringLabel: "Recurring Activity",
    formAddActivityButton: "Add Activity",
    formUpdateActivityButton: "Update Activity",
    formTimeRequiredAlert: "Activity name and time are required.",
    pageTitleLocation: "Location Services",
    pageSubtitleLocation: "Use the interactive map to find your way.",
    locationRefreshedSuccess: "Current location updated.",
    locationError: "Error getting location: {message}",
    homeSetSuccess: "Home location saved!",
    homeSetSpeech: "Home location has been set.",
    homeSetError: "Could not set home location. Current location unknown.",
    guideHomeError: "Cannot guide home, current location unknown. Try refreshing location.",
    guideHomeNotSetInfo: "Home location is not set. Please set it first.",
    destinationMissingInfo: "Please enter a destination.",
    notifyFamilySuccess: "Simulated: Notifying your family at {emails} that you are leaving.",
    notifyFamilyNoEmails: "No family emails found. Please add contacts in Family Settings to send notifications.",
    currentLocationTitle: "Current Location",
    findingLocation: "Finding your location...",
    latitude: "Latitude",
    longitude: "Longitude",
    refreshLocationButton: "Refresh Location",
    homeSettingsTitle: "Home Settings",
    homeSetLocationInfo: "Home is set to: Lat {lat}, Lon {lon}",
    homeNotSetInfo: 'Home location not set. Go to your home and click "Set Current Location as Home".',
    setHomeButton: "Set Current Location as Home",
    saveLocationButton: "Save This Spot",
    modalSaveLocationTitle: "Save Current Location",
    modalEditLocationTitle: "Edit Location Name",
    formLocationNameLabel: "Location Name",
    formLocationNamePlaceholder: "e.g., Park Entrance, Library",
    formSaveLocationButton: "Save Location",
    formUpdateLocationButton: "Update Name",
    locationNameRequired: "Location name is required.",
    locationSavedSuccess: 'Location "{name}" saved successfully.',
    savedLocationUpdatedSuccess: 'Location "{name}" updated successfully.',
    locationDeletedInfo: "Saved location has been deleted.",
    confirmDeleteLocation: 'Are you sure you want to delete the saved location "{name}"?',
    savedPlacesSectionTitle: "My Saved Places",
    noSavedPlaces: "You haven't saved any places yet. Use the 'Save This Spot' button to add one.",
    guideHereButton: "Guide Me Here",
    navigationHelpTitle: "Route Planner",
    guideHomeButton: "Guide Me Home",
    destinationLabel: "Where do you want to go?",
    destinationPlaceholder: "e.g., Post Office, Doctor's Clinic",
    guideToDestinationButton: "Guide to Destination",
    gettingDirections: "Calculating route...",
    directionsTitle: "Route Steps:",
    readDirectionsButton: "Read Directions",
    safetyActionsTitle: "Safety Actions",
    notifyFamilyButton: "Notify Family",
    notifyFamilyEmailSubject: "Location Update from MemoryCare",
    notifyFamilyEmailBody: "I am sharing my current location.\nLatitude: {lat}\nLongitude: {lon}\n\nView on Google Maps: https://www.google.com/maps?q={lat},{lon}",
    mapError: "Could not load the map. Please check your connection and try again.",
    mapApiKeyError: "Goong API key (GOONG_API_KEY) is not configured. This is different from the Gemini key.",
    geocodeError: "Could not find the location '{destination}'. Please try a different name or address.",
    directionsError: "Could not calculate a route. The destination may be unreachable.",
    pageTitleSettings: "Settings",
    pageSubtitleSettings: "Manage general settings, contacts, and application data.",
    addFamilyEmailButton: "Add Email",
    familyEmailInputPlaceholder: "Family member's email",
    noFamilyEmails: "No family members have been added yet.",
    familyEmailAddedSuccess: "{email} has been added to your family list.",
    familyEmailExistsError: "{email} is already in the list.",
    familyEmailInvalidError: "Please enter a valid email address.",
    familyEmailDeletedInfo: "{email} has been removed from the list.",
    confirmDeleteEmail: "Are you sure you want to remove {email}?",
    sharePlanButton: "Share Plan",
    sharePlanSuccess: "Simulated: Today's plan has been sent to {emails}.",
    sharePlanNoEmails: "No family emails found. Please add contacts in Family Settings to share your plan.",
    sharePlanEmailSubject: "Daily Plan from MemoryCare",
    sharePlanEmailBodyHeader: "Here is the schedule for today:\n\n",
    familyContactsSectionTitle: "Family Contacts",
    dataManagementTitle: "Data Management",
    dataManagementSubtitle: "Backup your data to a file or restore it from a backup.",
    exportDataButton: "Export Data",
    importDataButton: "Import Data",
    importConfirmTitle: "Confirm Import",
    importConfirmMessage: "Choose how to import the data. 'Merge' will add new items and update existing ones from the file. 'Overwrite' will delete all current data and replace it with the backup.",
    mergeDataButton: "Merge Data",
    overwriteDataButton: "Overwrite All Data",
    importSuccessMerge: "Data merged successfully! The app will now reload.",
    importSuccessOverwrite: "Data overwritten successfully! The app will now reload.",
    importErrorInvalidFile: "Import failed. The selected file is not a valid MemoryCare backup file.",
    importErrorReadFile: "Import failed. Could not read the selected file.",
    aiWelcomeMessage: "Hello! I'm your friendly assistant. How can I help you remember something today?",
    aiPlaceholder: "Ask me a question...",
    pageTitleMyStory: "My Story",
    pageSubtitleMyStory: "A living story of your life, updated with each memory you share.",
    myStoryAIQuestionTitle: "A Question for Today",
    myStoryYourAnswerTitle: "Your Answer",
    myStoryAnswerPlaceholder: "Share your thoughts and memories here...",
    myStorySaveAndUpdateButton: "Update My Story",
    myStoryTitle: "My Life Story",
    myStoryInitialStory: "Your story will be written here as you answer the questions. Let's begin by answering the first question.",
    myStoryLoadingStory: "Weaving your memories into a beautiful story...",
    myStoryLoadingQuestion: "Thinking of a new question for you...",
    myStoryMicrophoneButtonStart: "Record Answer",
    myStoryMicrophoneButtonStop: "Stop Recording",
    notificationPermissionBannerTitle: "Enable Notifications",
    notificationPermissionBannerBody: "Get timely reminders for your scheduled activities, even when the app is in the background.",
    locationPermissionBannerTitle: "Enable Location Services",
    locationPermissionBannerBody: "To provide navigation and map features, this app needs to access your device's location.",
    enableButton: "Enable",
    notNowButton: "Not Now",
    locationPermissionDeniedTitle: "Location Access Denied",
    locationPermissionDeniedBody: "To use map features, please enable location permissions for this site in your browser settings.",
    locationRequiredForMap: "Location access is required for map features.",
    enableLocationToBegin: "Please enable location to begin.",
  },
  vi: {
    headerTitle: "MemoryCare",
    navHome: "Trang Chủ",
    navMemoryLog: "Nhật Ký",
    navPlanner: "Kế hoạch",
    navLocation: "Vị Trí",
    navMyStory: "Câu Chuyện Của Tôi",
    navSettings: "Cài Đặt",
    footerText: "MemoryCare © {year}",
    language: "Ngôn ngữ",
    welcomeTitle: "Tổng quan hôm nay",
    welcomeSubtitle: "Đây là các hoạt động trong ngày của bạn.",
    welcomeMessage: "Ứng dụng này sẽ giúp bạn sắp xếp công việc hàng ngày, ghi nhớ những điều quan trọng và luôn kết nối với người thân.",
    todaysSchedule: "Lịch trình hôm nay",
    noActivitiesToday: "Hôm nay chưa có hoạt động nào. Bạn có muốn bắt đầu lập kế hoạch không?",
    goToPlanner: "Tới trang Kế hoạch",
    familiarFace: "Gương mặt thân quen",
    noPeopleToAdd: "Chưa có ai trong danh bạ. Bạn hãy thêm người thân để bắt đầu.",
    goToMemoryLog: "Tới trang Nhật ký",
    quickActions: "Tác vụ nhanh",
    featureMemoryLogTitle: "Nhật ký Kỷ niệm",
    featureMemoryLogDesc: "Lưu giữ thông tin về người thân và những suy nghĩ hàng ngày.",
    featurePlannerTitle: "Lập Kế hoạch",
    featurePlannerDesc: "Lên kế hoạch cho các hoạt động và nhận lời nhắc.",
    featureLocationTitle: "Dịch vụ Vị trí",
    featureLocationDesc: "Hỗ trợ tìm đường và giữ an toàn cho bạn.",
    reminderTitle: "Lời nhắn gửi yêu thương",
    reminderText: "Mỗi ngày đều là một hành trình mới. Luôn có chúng tôi ở đây đồng hành cùng bạn. Khi cần trợ giúp, đừng ngần ngại liên hệ với người chăm sóc hoặc người thân của bạn.",
    pageTitleMemoryLog: "Nhật ký Kỷ niệm",
    pageSubtitleMemoryLog: "Lưu giữ kỷ niệm về những người thân yêu và ghi lại nhật ký mỗi ngày.",
    personAddedSuccess: "Đã thêm {name} thành công!",
    personUpdatedSuccess: "Đã cập nhật {name} thành công.",
    personDeletedInfo: "Đã xóa thông tin của người này.",
    confirmDeletePerson: "Bạn có chắc muốn xóa người này không?",
    journalSavedSuccess: "Đã lưu ghi chú thành công!",
    journalNoSpeechInfo: "Không nhận dạng được giọng nói. Vui lòng thử lại.",
    confirmDeleteJournal: "Bạn có chắc muốn xóa ghi chú này không?",
    journalDeletedInfo: "Đã xóa ghi chú.",
    ttsNotSupportedError: "Tính năng đọc không được hỗ trợ trên thiết bị này.",
    ttsLanguageUnavailableError: "Không tìm thấy giọng đọc tiếng Việt trên thiết bị. Tính năng đọc sẽ không hoạt động.",
    peopleSectionTitle: "Người thân",
    addPersonButton: "Thêm Người thân",
    noPeopleYet: 'Chưa có ai được thêm. Hãy bấm "Thêm Người thân" để bắt đầu.',
    recallButton: "Gợi Nhớ",
    editButton: "Sửa",
    deleteButton: "Xóa",
    personRecallSpeech: "Đây là {name}, là {relationship} của bạn. {keyInfo}",
    journalSectionTitle: "Ghi chú hàng ngày",
    journalDescription: "Dùng giọng nói để ghi lại những suy nghĩ, cảm xúc hay hoạt động trong ngày của bạn.",
    speechNotSupported: "Trình duyệt của bạn không hỗ trợ nhận dạng giọng nói.",
    listeningPlaceholder: "Tôi đang nghe...",
    recordedThoughtsPlaceholder: "Những gì bạn nói sẽ được ghi lại ở đây...",
    startRecordingButton: "Bắt đầu ghi âm",
    stopRecordingButton: "Dừng ghi âm",
    saveEntryButton: "Lưu Ghi chú",
    pastEntriesTitle: "Các ghi chú trước đây:",
    readAloudButton: "Đọc to",
    modalAddPersonTitle: "Thêm người thân mới",
    modalEditPersonTitle: "Sửa thông tin {name}",
    formNameLabel: "Tên",
    formRelationshipLabel: "Mối quan hệ",
    formPhotoUrlLabel: "URL Ảnh hoặc Tải lên",
    formKeyInfoLabel: "Thông tin gợi nhớ",
    formCancelButton: "Hủy",
    formAddButton: "Thêm",
    formUpdateButton: "Cập nhật",
    formUploadButton: "Tải ảnh",
    formRequiredAlert: "Tên và mối quan hệ là bắt buộc.",
    pageTitlePlanner: "Kế hoạch trong ngày",
    pageSubtitlePlanner: "Lên lịch cho các hoạt động và nhận lời nhắc đúng giờ.",
    activityAddedSuccess: 'Đã thêm hoạt động "{name}".',
    activityUpdatedSuccess: 'Đã cập nhật hoạt động "{name}".',
    activityDeletedInfo: "Đã xóa hoạt động.",
    confirmDeleteActivity: "Bạn có chắc muốn xóa hoạt động này không?",
    remindSentInfo: 'Đã gửi lời nhắc về hoạt động "{name}".',
    ttsAlertMessage: "Tính năng đọc không được hỗ trợ. Sẽ hiển thị thông báo thay thế.",
    activityReminderSpeech: "Nhắc nhở: Đã đến giờ {name} lúc {time}. {description}",
    pushNotificationTitle: "Nhắc nhở: {name}",
    pushNotificationBody: "Lịch trình lúc {time}",
    addActivityButton: "Thêm hoạt động",
    noActivitiesYet: 'Chưa có hoạt động nào được lên lịch. Hãy bấm "Thêm hoạt động" để bắt đầu.',
    remindButton: "Nhắc nhở",
    modalAddActivityTitle: "Thêm hoạt động mới",
    modalEditActivityTitle: "Sửa hoạt động",
    formActivityNameLabel: "Tên hoạt động",
    formTimeLabel: "Thời gian (Giờ:Phút)",
    formDescriptionLabel: "Mô tả (không bắt buộc)",
    formRecurringLabel: "Hoạt động lặp lại",
    formAddActivityButton: "Thêm",
    formUpdateActivityButton: "Cập nhật",
    formTimeRequiredAlert: "Tên hoạt động và thời gian là bắt buộc.",
    pageTitleLocation: "Định vị & Tìm đường",
    pageSubtitleLocation: "Dùng bản đồ để tìm đường đi dễ dàng hơn.",
    locationRefreshedSuccess: "Đã cập nhật vị trí hiện tại.",
    locationError: "Không thể lấy vị trí: {message}",
    homeSetSuccess: "Đã lưu vị trí nhà!",
    homeSetSpeech: "Vị trí nhà đã được lưu.",
    homeSetError: "Không thể lưu vị trí nhà vì chưa có vị trí hiện tại của bạn.",
    guideHomeError: "Không thể chỉ đường về nhà vì chưa biết vị trí hiện tại. Bạn hãy thử làm mới lại vị trí.",
    guideHomeNotSetInfo: "Bạn chưa lưu vị trí nhà. Vui lòng lưu lại để dùng tính năng này.",
    destinationMissingInfo: "Vui lòng nhập điểm đến của bạn.",
    notifyFamilySuccess: "Đã chuẩn bị email để gửi thông báo cho người thân tại {emails}.",
    notifyFamilyNoEmails: "Chưa có email người thân. Vui lòng vào Cài đặt để thêm.",
    currentLocationTitle: "Vị trí hiện tại",
    findingLocation: "Đang tìm vị trí của bạn...",
    latitude: "Vĩ độ",
    longitude: "Kinh độ",
    refreshLocationButton: "Tải lại vị trí",
    homeSettingsTitle: "Vị trí nhà",
    homeSetLocationInfo: "Vị trí nhà: Vĩ độ {lat}, Kinh độ {lon}",
    homeNotSetInfo: 'Vị trí nhà chưa được đặt. Hãy đến nhà và bấm nút "Đặt vị trí hiện tại làm nhà".',
    setHomeButton: "Đặt vị trí hiện tại làm nhà",
    saveLocationButton: "Lưu địa điểm này",
    modalSaveLocationTitle: "Lưu vị trí hiện tại",
    modalEditLocationTitle: "Sửa tên vị trí",
    formLocationNameLabel: "Tên vị trí",
    formLocationNamePlaceholder: "ví dụ: Lối vào công viên, Thư viện",
    formSaveLocationButton: "Lưu vị trí",
    formUpdateLocationButton: "Cập nhật tên",
    locationNameRequired: "Bạn cần nhập tên vị trí.",
    locationSavedSuccess: 'Đã lưu vị trí "{name}" thành công.',
    savedLocationUpdatedSuccess: 'Đã cập nhật vị trí "{name}" thành công.',
    locationDeletedInfo: "Đã xóa vị trí đã lưu.",
    confirmDeleteLocation: 'Bạn có chắc muốn xóa vị trí đã lưu "{name}" không?',
    savedPlacesSectionTitle: "Địa Điểm Đã Lưu",
    noSavedPlaces: "Bạn chưa lưu địa điểm nào. Hãy dùng nút 'Lưu địa điểm này' để thêm.",
    guideHereButton: "Chỉ đường đến đây",
    navigationHelpTitle: "Tìm đường đi",
    guideHomeButton: "Chỉ đường về nhà",
    destinationLabel: "Bạn muốn đi đâu?",
    destinationPlaceholder: "ví dụ: Bưu điện, Phòng khám bác sĩ",
    guideToDestinationButton: "Tìm đường",
    gettingDirections: "Đang tìm đường...",
    directionsTitle: "Chỉ dẫn đường đi:",
    readDirectionsButton: "Đọc chỉ đường",
    safetyActionsTitle: "Hỗ trợ an toàn",
    notifyFamilyButton: "Báo cho người thân",
    notifyFamilyEmailSubject: "Cập Nhật Vị Trí từ MemoryCare",
    notifyFamilyEmailBody: "Tôi đang chia sẻ vị trí hiện tại của mình.\nVĩ độ: {lat}\nKinh độ: {lon}\n\nXem trên Google Maps: https://www.google.com/maps?q={lat},{lon}",
    mapError: "Không tải được bản đồ. Bạn vui lòng kiểm tra lại kết nối mạng.",
    mapApiKeyError: "Khóa API Goong (GOONG_API_KEY) chưa được cấu hình. Khóa này khác với khóa Gemini.",
    geocodeError: "Không tìm thấy địa điểm '{destination}'. Vui lòng thử một tên hoặc địa chỉ khác.",
    directionsError: "Không thể tìm được đường đi. Điểm đến có thể không tồn tại hoặc không thể đi tới.",
    pageTitleSettings: "Cài đặt",
    pageSubtitleSettings: "Quản lý cài đặt chung, danh bạ người thân và dữ liệu.",
    addFamilyEmailButton: "Thêm",
    familyEmailInputPlaceholder: "Email của người thân",
    noFamilyEmails: "Chưa có email người thân nào.",
    familyEmailAddedSuccess: "Đã thêm {email} vào danh sách người thân.",
    familyEmailExistsError: "{email} đã có trong danh sách.",
    familyEmailInvalidError: "Địa chỉ email không hợp lệ. Bạn vui lòng kiểm tra lại.",
    familyEmailDeletedInfo: "Đã xóa {email} khỏi danh sách.",
    confirmDeleteEmail: "Bạn có chắc muốn xóa {email} không?",
    sharePlanButton: "Chia sẻ lịch trình",
    sharePlanSuccess: "Lịch trình hôm nay đã sẵn sàng để gửi tới {emails}.",
    sharePlanNoEmails: "Chưa có email người thân. Vui lòng vào Cài đặt để thêm liên hệ và chia sẻ lịch trình.",
    sharePlanEmailSubject: "Lịch trình hàng ngày từ MemoryCare",
    sharePlanEmailBodyHeader: "Đây là lịch trình cho hôm nay:\n\n",
    familyContactsSectionTitle: "Danh bạ người thân",
    dataManagementTitle: "Quản lý Dữ liệu",
    dataManagementSubtitle: "Sao lưu dữ liệu của bạn ra tệp hoặc khôi phục lại từ bản sao lưu.",
    exportDataButton: "Sao lưu Dữ liệu",
    importDataButton: "Phục hồi Dữ liệu",
    importConfirmTitle: "Xác nhận Phục hồi",
    importConfirmMessage: "Bạn muốn phục hồi dữ liệu theo cách nào? 'Hợp nhất' sẽ thêm các mục mới và cập nhật các mục hiện có từ tệp. 'Ghi đè' sẽ xóa tất cả dữ liệu hiện tại và thay thế bằng bản sao lưu.",
    mergeDataButton: "Hợp nhất",
    overwriteDataButton: "Ghi đè",
    importSuccessMerge: "Đã hợp nhất dữ liệu thành công! Ứng dụng sẽ khởi động lại.",
    importSuccessOverwrite: "Đã phục hồi dữ liệu thành công! Ứng dụng sẽ khởi động lại.",
    importErrorInvalidFile: "Phục hồi thất bại. Tệp bạn chọn không phải là tệp sao lưu hợp lệ của MemoryCare.",
    importErrorReadFile: "Phục hồi thất bại. Không thể đọc được tệp bạn đã chọn.",
    aiWelcomeMessage: "Xin chào, tôi là trợ lý ảo của bạn đây. Hôm nay, bạn muốn tôi giúp gợi nhớ về điều gì nào?",
    aiPlaceholder: "Hỏi tôi bất cứ điều gì...",
    pageTitleMyStory: "Câu Chuyện Của Tôi",
    pageSubtitleMyStory: "Cuốn tự truyện về cuộc đời bạn, được vun đắp từ những ký ức bạn chia sẻ mỗi ngày.",
    myStoryAIQuestionTitle: "Gợi ý cho hôm nay",
    myStoryYourAnswerTitle: "Hồi ức của bạn",
    myStoryAnswerPlaceholder: "Hãy chia sẻ những dòng suy nghĩ và ký ức của bạn ở đây...",
    myStorySaveAndUpdateButton: "Cập nhật câu chuyện",
    myStoryTitle: "Câu Chuyện Cuộc Đời Tôi",
    myStoryInitialStory: "Câu chuyện của bạn sẽ được viết nên từ những câu trả lời. Hãy bắt đầu với câu hỏi đầu tiên.",
    myStoryLoadingStory: "Đang dệt nên câu chuyện tuyệt đẹp từ ký ức của bạn...",
    myStoryLoadingQuestion: "Đang nghĩ câu hỏi tiếp theo cho bạn...",
    myStoryMicrophoneButtonStart: "Ghi âm câu trả lời",
    myStoryMicrophoneButtonStop: "Dừng ghi âm",
    notificationPermissionBannerTitle: "Bật thông báo",
    notificationPermissionBannerBody: "Nhận lời nhắc kịp thời cho các hoạt động đã lên lịch, ngay cả khi ứng dụng chạy nền.",
    locationPermissionBannerTitle: "Bật Dịch vụ Vị trí",
    locationPermissionBannerBody: "Để cung cấp tính năng bản đồ và chỉ đường, ứng dụng cần truy cập vị trí thiết bị của bạn.",
    enableButton: "Bật",
    notNowButton: "Để sau",
    locationPermissionDeniedTitle: "Truy cập vị trí bị từ chối",
    locationPermissionDeniedBody: "Để sử dụng các tính năng bản đồ, vui lòng bật quyền truy cập vị trí cho trang web này trong cài đặt trình duyệt của bạn.",
    locationRequiredForMap: "Cần truy cập vị trí để sử dụng tính năng bản đồ.",
    enableLocationToBegin: "Vui lòng bật vị trí để bắt đầu.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useLocalStorage<Language>('language', 'vi');

  const t = useCallback((key: keyof typeof translations['en'], ...args: (string | number)[]) => {
    let translation = translations[language]?.[key] || translations['en'][key];
    
    // Sequentially replace placeholders to avoid issues with global regex state
    args.forEach(arg => {
        translation = translation.replace(/\{[^{}]+\}/, String(arg));
    });

    return translation;
  }, [language]);


  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
